spring.application.name=vulnapp
server.port=8080

spring.datasource.url=jdbc:h2:mem:vulndb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
# Intentional: hard-coded credential
spring.datasource.username=admin
spring.datasource.password=SuperSecret123!
spring.sql.init.mode=always

app.files.base-dir=/tmp/vulnapp-files
